//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orchestra.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orchestra.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvalonDock.
        /// </summary>
        internal static string AboutView_Links_0_Content {
            get {
                return ResourceManager.GetString("AboutView_Links_0_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://avalondock.codeplex.com.
        /// </summary>
        internal static string AboutView_Links_0_Url {
            get {
                return ResourceManager.GetString("AboutView_Links_0_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catel.
        /// </summary>
        internal static string AboutView_Links_1_Content {
            get {
                return ResourceManager.GetString("AboutView_Links_1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.catelproject.com.
        /// </summary>
        internal static string AboutView_Links_1_Url {
            get {
                return ResourceManager.GetString("AboutView_Links_1_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentRibbon.
        /// </summary>
        internal static string AboutView_Links_2_Content {
            get {
                return ResourceManager.GetString("AboutView_Links_2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fluent.codeplex.com.
        /// </summary>
        internal static string AboutView_Links_2_Url {
            get {
                return ResourceManager.GetString("AboutView_Links_2_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string AboutView_Links_Count {
            get {
                return ResourceManager.GetString("AboutView_Links_Count", resourceCulture);
            }
        }
    }
}
