<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <SelfContained>true</SelfContained>
    <AssemblyName>Orchestra.Examples.Ribbon.Fluent</AssemblyName>
    <RootNamespace>Orchestra.Examples.Ribbon</RootNamespace>
    <DefaultLanguage>en-US</DefaultLanguage>
    <SonarQubeExclude>true</SonarQubeExclude>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <UseWpf>true</UseWpf>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <StartupObject />
    <NoWarn>$(NoWarn);SA1652</NoWarn>
    <ApplicationIcon>Resources\Icons\Logo.ico</ApplicationIcon>
    <ApplicationManifest>.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Catel.Fody" Version="7.1.0-alpha0016" PrivateAssets="all" />
    <PackageReference Include="Catel.SourceGenerators" Version="7.1.0-alpha0064" PrivateAssets="all" />
    <PackageReference Include="Fluent.Ribbon" Version="11.0.2" />
    <PackageReference Include="Fody" Version="6.9.3" PrivateAssets="all">
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="LoadAssembliesOnStartup.Fody" Version="4.7.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.*" />
    <PackageReference Include="Orc.LogViewer" Version="6.0.0-alpha0112" />
    <PackageReference Include="Orc.Notifications" Version="6.0.0-alpha0139" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orchestra.Shell.Ribbon.Fluent\Orchestra.Shell.Ribbon.Fluent.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Orchestra.Examples.Shared\**\*.cs">
      <Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
    </Compile>
    <Page Include="..\Orchestra.Examples.Shared\**\*.xaml">
      <Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
    </Page>
  </ItemGroup>

  <Import Project="$(MSBuildProjectDirectory)\..\Directory.Build.shared.explicit.props" Condition="Exists('$(MSBuildProjectDirectory)\..\Directory.Build.shared.explicit.props')" />
  <Import Project="$(MSBuildProjectDirectory)\..\Directory.Build.shared.mat.props" Condition="Exists('$(MSBuildProjectDirectory)\..\Directory.Build.shared.mat.props')" />
</Project>
