//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orchestra.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orchestra.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string Orchestra_Assign {
            get {
                return ResourceManager.GetString("Orchestra_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to assign the input gesture to &apos;{0}&apos;. It will be removed from the other commands..
        /// </summary>
        internal static string Orchestra_AssignInputGestureAreYouSure {
            get {
                return ResourceManager.GetString("Orchestra_AssignInputGestureAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input gesture &apos;{0}&apos; is currently being used by the following commands:.
        /// </summary>
        internal static string Orchestra_AssignInputGestureUsedByFollowCommands {
            get {
                return ResourceManager.GetString("Orchestra_AssignInputGestureUsedByFollowCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Orchestra_Close {
            get {
                return ResourceManager.GetString("Orchestra_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Orchestra_Command {
            get {
                return ResourceManager.GetString("Orchestra_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string Orchestra_Customize {
            get {
                return ResourceManager.GetString("Orchestra_Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable logging.
        /// </summary>
        internal static string Orchestra_EnableLogging {
            get {
                return ResourceManager.GetString("Orchestra_EnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input gesture.
        /// </summary>
        internal static string Orchestra_InputGesture {
            get {
                return ResourceManager.GetString("Orchestra_InputGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts.
        /// </summary>
        internal static string Orchestra_KeyboardShortcuts {
            get {
                return ResourceManager.GetString("Orchestra_KeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press shortcut keys:.
        /// </summary>
        internal static string Orchestra_PressShortcutKeys {
            get {
                return ResourceManager.GetString("Orchestra_PressShortcutKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Orchestra_Print {
            get {
                return ResourceManager.GetString("Orchestra_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Orchestra_Remove {
            get {
                return ResourceManager.GetString("Orchestra_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace input gesture?.
        /// </summary>
        internal static string Orchestra_ReplaceInputGesture {
            get {
                return ResourceManager.GetString("Orchestra_ReplaceInputGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Orchestra_Reset {
            get {
                return ResourceManager.GetString("Orchestra_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting shortcuts will delete all your current shortcuts. This action cannot be undone. Are you sure you want to reset the shortcuts?.
        /// </summary>
        internal static string Orchestra_ResetKeyboardShortcutsAreYouSure {
            get {
                return ResourceManager.GetString("Orchestra_ResetKeyboardShortcutsAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut for selected command:.
        /// </summary>
        internal static string Orchestra_ShortcutForSelectedCommand {
            get {
                return ResourceManager.GetString("Orchestra_ShortcutForSelectedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts for {0}.
        /// </summary>
        internal static string Orchestra_ShortcutsForApplication {
            get {
                return ResourceManager.GetString("Orchestra_ShortcutsForApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show commands containing:.
        /// </summary>
        internal static string Orchestra_ShowCommandsContaining {
            get {
                return ResourceManager.GetString("Orchestra_ShowCommandsContaining", resourceCulture);
            }
        }
    }
}
