<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <AssemblyName>Orchestra.Examples.TaskRunner</AssemblyName>
    <RootNamespace>Orchestra.Examples.TaskRunner</RootNamespace>
    <DefaultLanguage>en-US</DefaultLanguage>
    <SonarQubeExclude>true</SonarQubeExclude>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <UseWpf>true</UseWpf>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <StartupObject />
    <NoWarn>$(NoWarn);SA1652</NoWarn>
    <ApplicationIcon>Resources\Icons\Logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Catel.Fody" Version="7.1.0-alpha0016" PrivateAssets="all" />
    <PackageReference Include="Catel.SourceGenerators" Version="7.1.0-alpha0083" PrivateAssets="all" />
    <PackageReference Include="Fody" Version="6.9.3" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="LoadAssembliesOnStartup.Fody" Version="4.7.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orchestra.Shell.TaskRunner\Orchestra.Shell.TaskRunner.csproj" />
  </ItemGroup>

  <Import Project="$(MSBuildProjectDirectory)\..\Directory.Build.shared.explicit.props" Condition="Exists('$(MSBuildProjectDirectory)\..\Directory.Build.shared.explicit.props')" />
  <Import Project="$(MSBuildProjectDirectory)\..\Directory.Build.shared.mat.props" Condition="Exists('$(MSBuildProjectDirectory)\..\Directory.Build.shared.mat.props')" />
</Project>
