//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("WildGums")]
[assembly: AssemblyVersion("5.2.0")]
[assembly: AssemblyFileVersion("5.2.0")]
[assembly: AssemblyInformationalVersion("5.2.0-alpha.1")]
[assembly: AssemblyCopyright("Copyright © WildGums 2010 - 2018")]

