//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("WildGums")]
[assembly: AssemblyVersion("5.1.6")]
[assembly: AssemblyFileVersion("5.1.6")]
[assembly: AssemblyInformationalVersion("5.1.6")]
[assembly: AssemblyCopyright("Copyright © WildGums 2014 - 2019")]

