name: Build and test

on:
  push:
    branches:
      - develop
      - master
  pull_request:
  
#permissions:
  #pull-requests: write
  #contents: write

jobs:
  build-and-test:
    runs-on: windows-latest # Required for some (WPF) projects
  
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        id: checkout
        with:
          fetch-depth: 0
          
      - name: Setup .NET Core
        id: setup-dotnet
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: '9.0.x'    
    
      - name: Cake Action
        id: cake-action
        uses: cake-build/cake-action@5167c3f6a9e15c76f009de2acdfb9488552bc0b9 #v3.0.0
        with:
          target: BuildAndTest
          arguments: |
            IsCiBuild: true